Gastos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [ path('admin/', admin.site.urls),
    			path('polls/', include('polls.urls') )	]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [ 
	#path( '', views.index, name='index' ),
	path( '', views.IndexView.as_view(), name = 'index' ),]
"""
	#path( '<int:question_id>/detail/', views.detail, name = 'detail' ),
	path( '<int:pk>/', views.DetailView.as_view(), name = 'detail' ),
	#path( '<int:question_id>/result/', views.result, name = 'result' ),
	path( '<int:pk>/result/', views.ResultView.as_view(), name = 'result'),
	#path( '<int:question_id>/vote/', views.vote, name = 'vote' ) ]
	path( '<int:question_id>/vote/', views.vote, name = 'vote' ) ]
"""

polls/models.py
from django.db import models
from django.utils import timezone
import datetime


# Create your models here.
class Gasto(models.Model):
	nombre_gasto = models.CharField( max_length = 200 )
	fecha = models.DateTimeField()
	cantidad = models.DecimalField( max_digits = 8, decimal_places = 6 )


"""
class Question( models.Model ):
	question_text = models.CharField( max_length = 200 )
	pub_date = models.DateTimeField( 'date published' )

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_descriptioon = 'Published recently?'

	def __str__(self):
		return self.question_text


class Choice( models.Model ):
	question = models.ForeignKey( Question, on_delete = models.CASCADE )
	choice_text = models.CharField( max_length = 150 )
	votes = models.IntegerField( default = 0 )

	def __str__(self):
		return self.choice_text
"""

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Gasto #,  Question, Choice


class IndexView( generic.ListView ):
	template_name = 'polls/index.html'
	context_object_name = 'lista_Gastos'

	def get_queryset(self):
		return Gasto.objects.order_by()[:]
		#return Question.objects.filter( pub_date__lte = timezone.now()).order_by( '-pub_date' )[:]



"""
detail
try:
	question = Question.objects.get( pk = question_id )
	return render( request, 'polls/detail.html',{'question':question} )
except Question.DoesNotExist:
	raise Http404("Question no existe.")


class DetailView( generic.DetailView ):
	model = Question
	template_name = 'polls/detail.html'
	
	def get_queryset(self):
		return Question.objects.filter( pub_date__lte = timezone.now() )


class ResultView(generic.DetailView):
	model = Question
	template_name = 'polls/result.html'


def index(request):
	latest_question = Question.objects.order_by('-pub_date')[:]
	template = loader.get_template('polls/index.html')
	context = { 'latest_question': latest_question }
	return HttpResponse( template.render( context, request ) )


def detail( request, question_id ):
	question = get_object_or_404( Question, pk = question_id)
	return render( request, 'polls/detail.html',{'question':question} )


def result( request, question_id ):
	question = get_object_or_404( Question, pk = question_id )
	return render( request, 'polls/result.html', { 'question': question } )


def vote( request, question_id ):
	question = get_object_or_404( Question, pk = question_id )
	selected_choice = None
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except ( KeyError, Choice.DoesNotExist ):
		return render( request, 'polls/detail.html',{ 'question':question, 'error_message':"tu no selecionaste nada hacker" } )
	else:
		selected_choice.votes += 1
		selected_choice.save()
		
		_url = reverse( 'polls:result', args = (question.id,) )

		return HttpResponseRedirect( _url )

"""

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
	<head>
		<title>Sistemas de Control de Gastos</title>
		<meta charset="utf-8">

	</head>
	<body>
		
		{% block branding %}
		<h1 id="site-name"><a href="{% url 'admin:index' %}">Administration</a></h1>
		{% endblock %}

		{% if latest_question %}
		    <ul>
		    {% for question in latest_question %}
		    	<!-- <li><a href="{% url 'polls:detail' question.id %}/">{{ question.question_text }}</a></li> -->
		        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
		    {% endfor %}
		    </ul>
		{% else %}
		    <p>No polls are available.</p>
		{% endif %}
		

		<table class="table">
			<thead class="thead-dark">
				<tr>
					<th scope="col">#</th>
					<th scope="col">Gasto</th>
					<th scope="col">Cantidad</th>
					<th scope="col">Fecha</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th scope="row">1</th>
					<td>x</td>
					<td>y</td>
					<td>z</td>
				</tr>
			</tbody>
		</table>
		
	</body>
</html>